/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iad_2_gg.gui;

import iad_2.gg.net.Network;
import iad_2.gg.net.TrainingData;
import iad_2_gg.services.DataHelper;
import iad_2_gg.services.GUIHelper;
import iad_2_gg.services.NetworkFactory;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author marr
 */
public class MainWindow extends javax.swing.JFrame {

    private static MainWindow INSTANCE;
    private FileChooserDialog fileChooserDialog;
    private List<JComboBox<String>> layerCombos = new ArrayList<>();
    private Network network;

    public static void showError(Exception ex, String text, String title) {
        JOptionPane.showMessageDialog(INSTANCE, text, title, JOptionPane.ERROR_MESSAGE);
    }

    public static void showInfo(String text, String title) {
        JOptionPane.showMessageDialog(INSTANCE, text, title, JOptionPane.INFORMATION_MESSAGE);
    }

    public Network getNetwork() {
        return network;
    }

    public void setNetwork(Network network) {
        this.network = network;

    }

    public static MainWindow getInstance() {
        return INSTANCE;
    }

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        INSTANCE = this;
        fileChooserDialog = new FileChooserDialog(this, true);
        fileChooserDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                fileChooserDialog.setVisible(false);
            }
        });
        initLookAndFeel();
        initComponents();
        collectLayersCombos();
        enableLayersCombos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboLayers = new javax.swing.JComboBox<>();
        jComboLayer2 = new javax.swing.JComboBox<>();
        jComboLayer1 = new javax.swing.JComboBox<>();
        jComboLayer3 = new javax.swing.JComboBox<>();
        jComboLayer4 = new javax.swing.JComboBox<>();
        jComboLayer5 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBias = new javax.swing.JCheckBox();
        jCheckRandomData = new javax.swing.JCheckBox();
        jButtonCreateFactory = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSliderEpochs = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboError = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboMomentum = new javax.swing.JComboBox<>();
        jComboError1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButtonCreateFactory1 = new javax.swing.JButton();
        jButtonCreateFactory2 = new javax.swing.JButton();
        jButtonCreateFactory3 = new javax.swing.JButton();
        jButtonCreateFactory4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextTestData = new javax.swing.JTextField();
        jButtonTestData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextTestResult = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jTextError = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButtonStdDataTraning = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inteligenta Analiza Danych");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Liczba warstw");

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Liczba neuronów w warstwach");

        jComboLayers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5" }));
        jComboLayers.setSelectedIndex(1);
        jComboLayers.setToolTipText("Łącznie z wartwą wejściową i wyjściową");
        jComboLayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboLayersActionPerformed(evt);
            }
        });

        jComboLayer2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboLayer2.setSelectedIndex(1);
        jComboLayer2.setEnabled(false);

        jComboLayer1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboLayer1.setSelectedIndex(3);
        jComboLayer1.setEnabled(false);

        jComboLayer3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboLayer3.setSelectedIndex(3);
        jComboLayer3.setEnabled(false);

        jComboLayer4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboLayer4.setEnabled(false);

        jComboLayer5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboLayer5.setEnabled(false);

        jCheckBias.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jCheckBias.setSelected(true);
        jCheckBias.setText("Bias");

        jCheckRandomData.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jCheckRandomData.setText("Kolejność losowa");
        jCheckRandomData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckRandomDataActionPerformed(evt);
            }
        });

        jButtonCreateFactory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCreateFactory.setText("Stwórz sieć");
        jButtonCreateFactory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateFactoryActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TESTOWANIE SIECI");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TRENOWANIE SIECI");

        jSliderEpochs.setMajorTickSpacing(100);
        jSliderEpochs.setMaximum(1000);
        jSliderEpochs.setMinimum(200);
        jSliderEpochs.setPaintLabels(true);
        jSliderEpochs.setPaintTicks(true);
        jSliderEpochs.setSnapToTicks(true);
        jSliderEpochs.setValue(1000);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Liczba epok");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Limit błędu");

        jComboError.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.00", "0.01", "0.05", "0.10", "0.20" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Człon momentum");

        jComboMomentum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9" }));

        jComboError1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9" }));
        jComboError1.setSelectedIndex(4);
        jComboError1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboError1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Współczynnik nauki");

        jButtonCreateFactory1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCreateFactory1.setText("Wczytaj z pliku");
        jButtonCreateFactory1.setActionCommand("importFromXML");
        jButtonCreateFactory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateFactory1ActionPerformed(evt);
            }
        });

        jButtonCreateFactory2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCreateFactory2.setText("Zapisz do pliku");
        jButtonCreateFactory2.setActionCommand("exportToXML");
        jButtonCreateFactory2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateFactory2ActionPerformed(evt);
            }
        });

        jButtonCreateFactory3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCreateFactory3.setText("Wczytaj wzorzec");
        jButtonCreateFactory3.setActionCommand("importPattern");
        jButtonCreateFactory3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateFactory3ActionPerformed(evt);
            }
        });

        jButtonCreateFactory4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCreateFactory4.setText("Trenuj sieć");
        jButtonCreateFactory4.setActionCommand("train");
        jButtonCreateFactory4.setEnabled(false);
        jButtonCreateFactory4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateFactory4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Wzorzec do testowania");

        jTextTestData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextTestData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTestDataActionPerformed(evt);
            }
        });

        jButtonTestData.setText("Testuj");
        jButtonTestData.setActionCommand("parseValues");
        jButtonTestData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestDataActionPerformed(evt);
            }
        });

        jTextTestResult.setEditable(false);
        jTextTestResult.setColumns(20);
        jTextTestResult.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTextTestResult.setRows(5);
        jScrollPane1.setViewportView(jTextTestResult);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Błąd po zakończeniu treningu");

        jTextError.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("<html>"+ "Trenowanie sieci wzorcami standarowymi" +"</html>");

        jButtonStdDataTraning.setText("Trenuj");
        jButtonStdDataTraning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStdDataTraningActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Wynik");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboLayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboLayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboLayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboLayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboLayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboLayers, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBias, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButtonTestData, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTestData, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboError1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSliderEpochs, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonCreateFactory3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButtonCreateFactory4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComboError, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextError, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(17, 17, 17)
                                    .addComponent(jButtonStdDataTraning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jComboMomentum, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckRandomData, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCreateFactory2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCreateFactory1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCreateFactory, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboLayers, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBias, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderEpochs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCreateFactory3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonCreateFactory4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(jLabel10))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboLayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jButtonStdDataTraning)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboLayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jComboLayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jComboLayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboMomentum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboError1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jComboLayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckRandomData, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCreateFactory, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jButtonCreateFactory1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCreateFactory2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextTestData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButtonTestData, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboLayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboLayersActionPerformed
        enableLayersCombos();
    }//GEN-LAST:event_jComboLayersActionPerformed

    private void jButtonCreateFactoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateFactoryActionPerformed
        createNetwork();
    }//GEN-LAST:event_jButtonCreateFactoryActionPerformed

    private void jCheckRandomDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckRandomDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckRandomDataActionPerformed

    private void jButtonCreateFactory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateFactory1ActionPerformed
        fileChooserDialog.setAction(evt.getActionCommand());
        fileChooserDialog.setVisible(true);
    }//GEN-LAST:event_jButtonCreateFactory1ActionPerformed

    private void jButtonCreateFactory2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateFactory2ActionPerformed
        fileChooserDialog.setAction(evt.getActionCommand());
        fileChooserDialog.setVisible(true);
    }//GEN-LAST:event_jButtonCreateFactory2ActionPerformed

    private void jButtonCreateFactory3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateFactory3ActionPerformed
        fileChooserDialog.setAction(evt.getActionCommand());
        fileChooserDialog.setVisible(true);
    }//GEN-LAST:event_jButtonCreateFactory3ActionPerformed

    private void jButtonCreateFactory4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateFactory4ActionPerformed
        try {
            network.trainNetwork(TrainingData.data,
                    TrainingData.expected,
                    Double.parseDouble((String) jComboError1.getSelectedItem()),
                    Double.parseDouble((String) jComboMomentum.getSelectedItem()),
                    jSliderEpochs.getValue(),
                    Double.parseDouble((String) jComboError.getSelectedItem()),
                    jCheckRandomData.isSelected());
        } catch (Exception ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        showErrorAfterTraining();
        ChartDialog chart = new ChartDialog(this, true, "Błąd kwadratowy", "epoka", "błąd", network.getLog(), 25);
        chart.setVisible(true);
    }//GEN-LAST:event_jButtonCreateFactory4ActionPerformed

    private void jComboError1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboError1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboError1ActionPerformed

    private void jTextTestDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTestDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTestDataActionPerformed

    private void jButtonTestDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestDataActionPerformed
        try {
            showTestResult(network.activate(GUIHelper.parseValues(jTextTestData.getText())));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sieć nie została utworzona", "Błąd sieci", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonTestDataActionPerformed

    private void jButtonStdDataTraningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStdDataTraningActionPerformed
        try {
            network.trainNetwork(DataHelper.GetInstance().GetStaticData(1),
                    DataHelper.GetInstance().GetStaticData(1),
                    Double.parseDouble((String) jComboError1.getSelectedItem()),
                    Double.parseDouble((String) jComboMomentum.getSelectedItem()),
                    jSliderEpochs.getValue(),
                    Double.parseDouble((String) jComboError.getSelectedItem()),
                    jCheckRandomData.isSelected());

        } catch (Exception ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        showErrorAfterTraining();
        ChartDialog chart = new ChartDialog(this, true, "Błąd kwadratowy", "epoka", "błąd", network.getLog(), 25);
        chart.setVisible(true);
    }//GEN-LAST:event_jButtonStdDataTraningActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateFactory;
    private javax.swing.JButton jButtonCreateFactory1;
    private javax.swing.JButton jButtonCreateFactory2;
    private javax.swing.JButton jButtonCreateFactory3;
    private javax.swing.JButton jButtonCreateFactory4;
    private javax.swing.JButton jButtonStdDataTraning;
    private javax.swing.JButton jButtonTestData;
    private javax.swing.JCheckBox jCheckBias;
    private javax.swing.JCheckBox jCheckRandomData;
    private javax.swing.JComboBox<String> jComboError;
    private javax.swing.JComboBox<String> jComboError1;
    private javax.swing.JComboBox<String> jComboLayer1;
    private javax.swing.JComboBox<String> jComboLayer2;
    private javax.swing.JComboBox<String> jComboLayer3;
    private javax.swing.JComboBox<String> jComboLayer4;
    private javax.swing.JComboBox<String> jComboLayer5;
    private javax.swing.JComboBox<String> jComboLayers;
    private javax.swing.JComboBox<String> jComboMomentum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSlider jSliderEpochs;
    private javax.swing.JTextField jTextError;
    private javax.swing.JTextField jTextTestData;
    private javax.swing.JTextArea jTextTestResult;
    // End of variables declaration//GEN-END:variables

    private void enableLayersCombos() {
        int layers = jComboLayers.getSelectedIndex() + 2;
        int i = 0;
        for (; i < layers; i++) {
            layerCombos.get(i).setEnabled(true);
        }
        for (; i < layerCombos.size(); i++) {
            layerCombos.get(i).setEnabled(false);
        }
    }

    private void createNetwork() {
        List<Integer> layers = new ArrayList<>();
        for (int i = 0; i < jComboLayers.getSelectedIndex() + 2; i++) {
            layers.add(layerCombos.get(i).getSelectedIndex() + 1);
        }
        int bias = 0;
        if (jCheckBias.isSelected()) {
            bias = 1;
        }
        try {
            network = NetworkFactory.GetNetwork(layers, bias);
            StringBuilder sb = new StringBuilder("");
            for (int i = 0; i < layers.get(0) - 1; i++) {
                sb.append("0,");
            }
            sb.append("0");
            jTextTestData.setText(sb.toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Liczba wejść i wyjść nie są sobie równe", "Błąd liczby neuronów", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void collectLayersCombos() {
        layerCombos.add(jComboLayer1);
        layerCombos.add(jComboLayer2);
        layerCombos.add(jComboLayer3);
        layerCombos.add(jComboLayer4);
        layerCombos.add(jComboLayer5);
    }

    private void showTestResult(double[] result) {
        jTextTestResult.setText("");
        DecimalFormat df = new DecimalFormat("0.####");
        for (double d : result) {
            jTextTestResult.append(df.format(d) + "\n");
        }
    }

    private void showErrorAfterTraining() {
        DecimalFormat df = new DecimalFormat("0.########");
        List<Double> errorLog = network.getLog();
        jTextError.setText(df.format(errorLog.get(errorLog.size() - 1)));
    }

    private static void initLookAndFeel() {
        String lookAndFeel = null;
        lookAndFeel = UIManager.getSystemLookAndFeelClassName();
        try {
            UIManager.setLookAndFeel(lookAndFeel);
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException e) {
        } catch (Exception e) {
            //TODO :)
        }
    }

    public void isTrainingEnabled(boolean b) {
        jButtonCreateFactory4.setEnabled(b);
    }
}
