/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iad_2_gg.gui;

import iad_2.gg.net.Network;
import iad_2_gg.services.DataParser;
import iad_2_gg.services.GUIHelper;
import iad_2_gg.services.NetworkHelper;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author marr
 */
public class MainWindow extends javax.swing.JFrame {

    private static MainWindow INSTANCE;
    private FileChooserDialog fileChooserDialog;
    private final List<JTextField> layerCombos = new ArrayList<>();
    private NetworkHelper networkHelper;
//    private Network network;
//    private DataParser dataParser;
//    private TrainingData data;

    public static void showError(Exception ex, String text, String title) {
        JOptionPane.showMessageDialog(INSTANCE, text, title, JOptionPane.ERROR_MESSAGE);
    }

    public static void showInfo(String text, String title) {
        JOptionPane.showMessageDialog(INSTANCE, text, title, JOptionPane.INFORMATION_MESSAGE);
    }

    public Network getNetwork() {
        return networkHelper.getNetwork();
    }

    public void setNetwork(Network network) {
        networkHelper.setNetwork(network);

    }

    public static MainWindow getInstance() {
        return INSTANCE;
    }

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        INSTANCE = this;
        fileChooserDialog = new FileChooserDialog(this, true);
        fileChooserDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                fileChooserDialog.setVisible(false);
            }
        });
        initLookAndFeel();
        initComponents();
        collectLayersCombos();
        enableLayersCombos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboLayers = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBias = new javax.swing.JCheckBox();
        jCheckRandomData = new javax.swing.JCheckBox();
        jButtonCreateFactory = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboError = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboMomentum = new javax.swing.JComboBox<>();
        jComboLearningRate = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButtonCreateFactory1 = new javax.swing.JButton();
        jButtonCreateFactory2 = new javax.swing.JButton();
        jButtonCreateFactory3 = new javax.swing.JButton();
        jButtonCreateFactory4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextTestData = new javax.swing.JTextField();
        jButtonTestData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextTestResult = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jTextError = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextLayer4 = new javax.swing.JTextField();
        jTextLayer1 = new javax.swing.JTextField();
        jTextLayer5 = new javax.swing.JTextField();
        jTextLayer2 = new javax.swing.JTextField();
        jTextLayer3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboSubData = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jTextExcluded = new javax.swing.JTextField();
        jButtonResetNetwork = new javax.swing.JButton();
        jTextEpochNumber = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextConfusionMatrix = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inteligenta Analiza Danych");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Liczba warstw");

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Liczba neuronów w warstwach");

        jComboLayers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5" }));
        jComboLayers.setSelectedIndex(1);
        jComboLayers.setToolTipText("Łącznie z wartwą wejściową i wyjściową");
        jComboLayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboLayersActionPerformed(evt);
            }
        });

        jCheckBias.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jCheckBias.setSelected(true);
        jCheckBias.setText("Bias");

        jCheckRandomData.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jCheckRandomData.setText("Kolejność losowa");
        jCheckRandomData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckRandomDataActionPerformed(evt);
            }
        });

        jButtonCreateFactory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCreateFactory.setText("Stwórz sieć");
        jButtonCreateFactory.setEnabled(false);
        jButtonCreateFactory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateFactoryActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TESTOWANIE SIECI");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TRENOWANIE SIECI");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Liczba epok");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Wyklucz dane");

        jComboError.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.00", "0.01", "0.05", "0.10", "0.20" }));
        jComboError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboErrorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Człon momentum");

        jComboMomentum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9" }));
        jComboMomentum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMomentumActionPerformed(evt);
            }
        });

        jComboLearningRate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.005", "0.01", "0.025", "0.05", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9" }));
        jComboLearningRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboLearningRateActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Współczynnik nauki");

        jButtonCreateFactory1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCreateFactory1.setText("Wczytaj z pliku");
        jButtonCreateFactory1.setActionCommand("importFromXML");
        jButtonCreateFactory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateFactory1ActionPerformed(evt);
            }
        });

        jButtonCreateFactory2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCreateFactory2.setText("Zapisz do pliku");
        jButtonCreateFactory2.setActionCommand("exportToXML");
        jButtonCreateFactory2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateFactory2ActionPerformed(evt);
            }
        });

        jButtonCreateFactory3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCreateFactory3.setText("Wczytaj wzorzec");
        jButtonCreateFactory3.setActionCommand("importPattern");
        jButtonCreateFactory3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateFactory3ActionPerformed(evt);
            }
        });

        jButtonCreateFactory4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCreateFactory4.setText("Trenuj sieć");
        jButtonCreateFactory4.setActionCommand("train");
        jButtonCreateFactory4.setEnabled(false);
        jButtonCreateFactory4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateFactory4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Wzorzec do testowania");

        jTextTestData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextTestData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTestDataActionPerformed(evt);
            }
        });

        jButtonTestData.setText("Testuj");
        jButtonTestData.setActionCommand("parseValues");
        jButtonTestData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestDataActionPerformed(evt);
            }
        });

        jTextTestResult.setEditable(false);
        jTextTestResult.setColumns(20);
        jTextTestResult.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTextTestResult.setRows(5);
        jScrollPane1.setViewportView(jTextTestResult);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Błąd po zakończeniu treningu");

        jTextError.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Wynik");

        jTextLayer4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextLayer4.setText("1");
        jTextLayer4.setEnabled(false);

        jTextLayer1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextLayer1.setText("4");
        jTextLayer1.setEnabled(false);

        jTextLayer5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextLayer5.setText("1");
        jTextLayer5.setEnabled(false);

        jTextLayer2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextLayer2.setText("4");
        jTextLayer2.setEnabled(false);

        jTextLayer3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextLayer3.setText("3");
        jTextLayer3.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Limit błędu");

        jComboSubData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wszystkie dane w zbiorze treningowym", "66 % trening, 18% walid. 18% test.", "66 % trening, 18% walid. 18% test. (losowo)", "40 % trening, 30% walid. 30% test.", "40 % trening, 30% walid. 30% test. (losowo)" }));
        jComboSubData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSubDataActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Podzbiór trenujący");

        jButtonResetNetwork.setText("Resetuj siec");
        jButtonResetNetwork.setEnabled(false);
        jButtonResetNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetNetworkActionPerformed(evt);
            }
        });

        jTextEpochNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextEpochNumber.setText("1000");

        jTextConfusionMatrix.setColumns(20);
        jTextConfusionMatrix.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextConfusionMatrix.setRows(5);
        jScrollPane2.setViewportView(jTextConfusionMatrix);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Tablica błędów");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCreateFactory2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCreateFactory1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCreateFactory, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextLayer5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextLayer3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextLayer2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextLayer4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextLayer1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboLayers, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBias, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextTestData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButtonTestData, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(131, 131, 131))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboError, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jTextEpochNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboLearningRate, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jButtonCreateFactory4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCreateFactory3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonResetNetwork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextError, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboSubData, 0, 233, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(jCheckRandomData, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(jComboMomentum, 0, 233, Short.MAX_VALUE)
                            .addComponent(jTextExcluded))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(365, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(363, 363, 363)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboLayers, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBias, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCreateFactory3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextEpochNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jTextLayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jTextLayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextLayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonCreateFactory4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonResetNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboLearningRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(14, 14, 14)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextLayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jTextLayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboMomentum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckRandomData, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jComboSubData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextExcluded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCreateFactory, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jButtonCreateFactory1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCreateFactory2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextTestData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTestData, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(359, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(348, 348, 348)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboLayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboLayersActionPerformed
        enableLayersCombos();
    }//GEN-LAST:event_jComboLayersActionPerformed

    private void jButtonCreateFactoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateFactoryActionPerformed
        createNetwork();
    }//GEN-LAST:event_jButtonCreateFactoryActionPerformed

    private void jCheckRandomDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckRandomDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckRandomDataActionPerformed

    private void jButtonCreateFactory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateFactory1ActionPerformed
        fileChooserDialog.setAction(evt.getActionCommand());
        fileChooserDialog.setVisible(true);
    }//GEN-LAST:event_jButtonCreateFactory1ActionPerformed

    private void jButtonCreateFactory2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateFactory2ActionPerformed
        fileChooserDialog.setAction(evt.getActionCommand());
        fileChooserDialog.setVisible(true);
    }//GEN-LAST:event_jButtonCreateFactory2ActionPerformed

    private void jButtonCreateFactory3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateFactory3ActionPerformed
        fileChooserDialog.setAction(evt.getActionCommand());
        fileChooserDialog.setVisible(true);
    }//GEN-LAST:event_jButtonCreateFactory3ActionPerformed

    private void jButtonCreateFactory4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateFactory4ActionPerformed
        jTextConfusionMatrix.setText("");
        try {
            networkHelper.starTraining(
                    Integer.parseInt(jTextEpochNumber.getText()),
                    Double.parseDouble((String) jComboLearningRate.getSelectedItem()),
                    Double.parseDouble((String) jComboMomentum.getSelectedItem()),
                    jCheckRandomData.isSelected(),
                    jComboSubData.getSelectedIndex(),
                    getExcludedList()
            );
        } catch (Network.NoNetworkException ex) {
            JOptionPane.showMessageDialog(this, "Sieć nie zostałą utworzona", "Błąd sieci", JOptionPane.ERROR_MESSAGE);
            return;
        } catch (Exception ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        showErrorAfterTraining();
        if (jComboSubData.getSelectedIndex() == 0) {
            ChartDialog chart = new ChartDialog(this, false, "Błąd zbioru treningowego ", "epoka", "błąd", networkHelper.getTrainingErrorLog(), "błąd", 50);
            chart.setVisible(true);
        } else {
            showConfusionMatrix(networkHelper.getConfusionMatrix());
            ChartDialog chart1 = new ChartDialog(this, false, "Błąd zbioru walidacyjnego", "epoka", "błąd",
                    networkHelper.getTrainingErrorLog(), "zbiór treningowy",
                    networkHelper.getValidationErrorLog(), "zbiór walidacyjny", 50);
            ChartDialog chart2 = new ChartDialog(this, false, "Odsetek poprawnie zaklasyfikowanych przykładów", "epoka", "%", networkHelper.getTestScoreLog(), "klasyfikacje", 50);
            chart2.setVisible(true);
            chart1.setVisible(true);
        }
    }//GEN-LAST:event_jButtonCreateFactory4ActionPerformed

    private void jComboLearningRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboLearningRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboLearningRateActionPerformed

    private void jTextTestDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTestDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTestDataActionPerformed

    private void jButtonTestDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestDataActionPerformed
        try {
            showTestResult(networkHelper.getResult(GUIHelper.parseValues(jTextTestData.getText())));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Niepoprawny format danych", "Błąd danych", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonTestDataActionPerformed

    private void jComboErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboErrorActionPerformed

    private void jComboMomentumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMomentumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboMomentumActionPerformed

    private void jComboSubDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSubDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboSubDataActionPerformed

    private void jButtonResetNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetNetworkActionPerformed
        createNetwork();
    }//GEN-LAST:event_jButtonResetNetworkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateFactory;
    private javax.swing.JButton jButtonCreateFactory1;
    private javax.swing.JButton jButtonCreateFactory2;
    private javax.swing.JButton jButtonCreateFactory3;
    private javax.swing.JButton jButtonCreateFactory4;
    private javax.swing.JButton jButtonResetNetwork;
    private javax.swing.JButton jButtonTestData;
    private javax.swing.JCheckBox jCheckBias;
    private javax.swing.JCheckBox jCheckRandomData;
    private javax.swing.JComboBox<String> jComboError;
    private javax.swing.JComboBox<String> jComboLayers;
    private javax.swing.JComboBox<String> jComboLearningRate;
    private javax.swing.JComboBox<String> jComboMomentum;
    private javax.swing.JComboBox<String> jComboSubData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextConfusionMatrix;
    private javax.swing.JTextField jTextEpochNumber;
    private javax.swing.JTextField jTextError;
    private javax.swing.JTextField jTextExcluded;
    private javax.swing.JTextField jTextLayer1;
    private javax.swing.JTextField jTextLayer2;
    private javax.swing.JTextField jTextLayer3;
    private javax.swing.JTextField jTextLayer4;
    private javax.swing.JTextField jTextLayer5;
    private javax.swing.JTextField jTextTestData;
    private javax.swing.JTextArea jTextTestResult;
    // End of variables declaration//GEN-END:variables

    private void enableLayersCombos() {
        int layers = jComboLayers.getSelectedIndex() + 2;
        int i = 0;
        for (; i < layers; i++) {
            layerCombos.get(i).setEnabled(true);
        }
        for (; i < layerCombos.size(); i++) {
            layerCombos.get(i).setEnabled(false);
        }
    }

    private void createNetwork() {
        List<Integer> layers = new ArrayList<>();
        for (int i = 0; i < jComboLayers.getSelectedIndex() + 2; i++) {
            layers.add(Integer.parseInt(layerCombos.get(i).getText()));
        }
        int bias = 0;
        if (jCheckBias.isSelected()) {
            bias = 1;
        }
        try {
            networkHelper.setUpNetwork(layers, bias);
            StringBuilder sb = new StringBuilder("");
            for (int i = 0; i < layers.get(0) - 1; i++) {
                sb.append("0,");
            }
            sb.append("0");
            jTextTestData.setText(sb.toString());
            jButtonCreateFactory4.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Błąd sieci", "Błąd liczby neuronów", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void collectLayersCombos() {
        layerCombos.add(jTextLayer1);
        layerCombos.add(jTextLayer2);
        layerCombos.add(jTextLayer3);
        layerCombos.add(jTextLayer4);
        layerCombos.add(jTextLayer5);
    }

    private void showTestResult(double[] result) {
        jTextTestResult.setText("");
        DecimalFormat df = new DecimalFormat("0.####");
        for (double d : result) {
            jTextTestResult.append(df.format(d) + "\n");
        }
    }

    private void showErrorAfterTraining() {
        DecimalFormat df = new DecimalFormat("0.########");
        List<Double> errorLog = networkHelper.getTrainingErrorLog();
        jTextError.setText(df.format(errorLog.get(errorLog.size() - 1)));
    }

    private static void initLookAndFeel() {
        String lookAndFeel = null;
        lookAndFeel = UIManager.getSystemLookAndFeelClassName();
        try {
            UIManager.setLookAndFeel(lookAndFeel);
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException e) {
        } catch (Exception e) {
            //TODO :)
        }
    }

    private List<Integer> getExcludedList() {
        List<Integer> excluded = new ArrayList<>();
        String input = jTextExcluded.getText();
        if (!input.isEmpty()) {
            String[] split = input.split(",");
            for (String s : split) {
                excluded.add(Integer.parseInt(s));
            }
        }
        return excluded;
    }

    public void isTrainingEnabled(DataParser trainingData) {
        this.networkHelper = new NetworkHelper(trainingData);
        jButtonCreateFactory.setEnabled(true);
        jButtonResetNetwork.setEnabled(true);
    }

    public void showConfusionMatrix(List<List<Integer>> matrix){
        StringBuilder sb = new StringBuilder("");
        sb.append("\t");
        int it = 0;
        for (Integer i : matrix.get(0)){
            sb.append(++it).append("\t");
        }
        sb.append("\n");
        for (int i = 0; i < matrix.size(); i++){
            sb.append(i + 1).append("\t");
            for (Integer j : matrix.get(i)){
                sb.append(j).append("\t");
            }
            sb.append("\n");
        }
        jTextConfusionMatrix.setText(sb.toString());
    }
}
